version: 2
updates:
  - package-ecosystem: gomod
    directory: /keyloader
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /pki
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /mtls
    schedule:
      interval: weekly