version: 2
updates:
  - package-ecosystem: gomod
    directory: /certkit
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /schedule
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /throttle
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /lifecycle
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /retry
    schedule:
      interval: weekly
